# Minimal MI configuration for ICP registration

[dashboard_config]
dashboard_url = "https://icp:9743/dashboard/api/"
heartbeat_interval = 5
group_id = "sandbox"
node_id = "mi-node-1"

[internal_apis]
enabled = true

[internal_apis.health_check]
enable = true
